# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c93a661f5fccabe45bab35ec6c29d5f8d0788978ed687fcea586eb0f54dc2e0293cdcd19cfd33ddf6b15fd81336d08777ff5f22e0fae743adaea0cc2e506ee36

test:
  secret_key_base: a856931fdcced05cbb32ff9634a9d82524ec01b6ae84a275311324e082e06be05c79c91fe0c3a17394fce499d4011a45d4df9ba64450ed6562a30119909bf325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
